# Problem 1

In [16]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.random.randint(0,10,5)
print(a)
# 3 - matris'in boyutunu öğrenin
print(a.ndim)
# 4 - matris'i yeniden boyutlandırın
print(a.reshape(5,1))
# 5 - matris'in boyut sayısını öğrenin
print(a.size)

[8 0 3 0 7]
1
[[8]
 [0]
 [3]
 [0]
 [7]]
5


# Problem 2

In [17]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
b = np.arange(1,11, 2)
print(b)
# 2 - Oluşturduğunuz matrisi parçalayın
c,d,e = np.split(b,[2,4])
print(c)
print(d)
print(e)
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([c,d,e]))

[1 3 5 7 9]
[1 3]
[5 7]
[9]
[1 3 5 7 9]


# Problem 3

In [21]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
f = np.random.randint(5,100,size=10)
f
# 2 - matris'in özelliklerini inceleyin
print(f.ndim)
print(f.size)
print(f.dtype)
print(f.shape)

1
10
int64
(10,)
