# Problem 1 

In [5]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
myArray = np.array([2,3,4,5,1])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
myArray.sort()
myArray


array([1, 2, 3, 4, 5])

# Problem 2

In [34]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
array = np.array([10,15,30,45,60])
print(array)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
array2 = np.arange(5,15)
print(array2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
array3 = np.arange(50,100,5)
print(array3)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
array4 = np.zeros(10)
print(array4)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
array5 = np.ones(10)
print(array5)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
array6 = np.linspace(0,100,5)
print(array6)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
array7 = np.random.randint(10,30,5)
print(array7)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
array8 = np.random.uniform(-1,1,10)
print(array8)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
array9 = np.random.randint(10,50,(3,5))
print(array9)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(array9.sum(axis=0))
print(array9.sum(axis=1))
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(array9.max())
print(array9.min())
print(array9.mean())
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(array9.argmax())
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
array13 = np.arange(10,20)
print(array13[:3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(array13[::-1])
# 15- Üretilen matrisin ilk satırını seçiniz.
print(array9[0,:5])
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(array9[1,2])
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(array9[:3,0])
# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(array9**2)
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
array10 = np.random.randint(-50,50,(3,5))
pozCift = []

for a in range(array10.shape[0]):
    for b in range(array10.shape[1]):
        if array10[a,b] > 0 and array10[a,b] % 2 == 0:
            pozCift.append(array10[a,b])
print(array10)
print(pozCift) 


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[23 11 16 18 14]
[ 0.70972659 -0.36090066 -0.61854445  0.43119182  0.66707562  0.47860429
  0.62207479  0.89162136 -0.66798361  0.60680355]
[[34 13 47 47 33]
 [44 29 23 36 15]
 [38 41 40 31 24]]
[116  83 110 114  72]
[174 147 174]
47
13
33.0
2
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[34 13 47 47 33]
23
[34 44 38]
[[1156  169 2209 2209 1089]
 [1936  841  529 1296  225]
 [1444 1681 1600  961  576]]
[[ 24  -4  49   3 -47]
 [-19  27  23 -38 -20]
 [ 44 -24 -17 -38   8]]
[24, 44, 8]
